language: python
python:
- "3.6"
install: "pip install -r requirements.txt"
script:
SECRET_KEY="whatever" python manage.py test

# configure which branches to run
branches:
  # whitelist
  only:
    - master
    - /^deploy-.*$/ # regex ok
  # blacklist
  except:
    - dontrunme 
    - test 